app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('api/v1/', include('authentication.urls')),

    path('', views.home, name='home'),
    path('', include('brands.urls')),
    path('', include('categories.urls')),
    path('', include('suppliers.urls')),
    path('', include('inflows.urls')),
    path('', include('outflows.urls')),
    path('', include('products.urls')),
]

categories/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('categories/list/', views.CategoryListView.as_view(), name='category_list'),
    path('categories/create/', views.CategoryCreateView.as_view(), name='category_create'),
    path('categories/<int:pk>/detail/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('categories/<int:pk>/update/', views.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/<int:pk>/delete/', views.CategoryDeleteView.as_view(), name='category_delete'),

    path('api/v1/categories/', views.CategoryCreateListAPIView.as_view(), name='category-create-list-api-view'),
    path('api/v1/categories/<int:pk>/', views.CategoryRetrieveUpdateDestroyAPIView.as_view(), name='category-detail-api-view')
]

categories/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=500)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

categories/forms.py
from django import forms
from . import models


class CategoryForm(forms.ModelForm):

    class Meta:
        model = models.Category
        fields = ['name', 'description']  # Adicione os campos necessários do modelo Category
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),  # Aplicando classe CSS do bootstrap
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),  # Aplicando classe CSS  e numero de linhas
        }
        labels = {
            'name': 'Nome da Categoria',
            'description': 'Descrição da Categoria',
        }

categories/views.py
from rest_framework import generics
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from . import models, forms, serializers


class CategoryListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = models.Category
    template_name = 'category_list.html'
    context_object_name = 'categories'  # nome do model no plural e minúsculo
    paginate_by = 10  # Número de items por página
    permission_required = 'categories.view_category'

    def get_queryset(self):  # Sobrescreve o método get_queryset, que retorna todas as categories
        queryset = super().get_queryset()
        name = self.request.GET.get('name')  # Pega o parâmetro 'name' da URL

        if name:
            queryset = queryset.filter(name__icontains=name)  # Filtra as categories pelo nome, ignorando maiúsculas/minúsculas

        return queryset


class CategoryCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = models.Category
    template_name = 'category_create.html'
    form_class = forms.CategoryForm
    success_url = reverse_lazy('category_list')  # Redireciona para a lista de categories após a criação
    permission_required = 'categories.add_category'


class CategoryDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = models.Category
    template_name = 'category_detail.html'
    context_object_name = 'object'
    permission_required = 'categories.view_category'


class CategoryUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = models.Category
    template_name = 'category_update.html'
    form_class = forms.CategoryForm
    success_url = reverse_lazy('category_list')  # Redireciona para a lista de categories após a criação
    permission_required = 'categories.change_category'


class CategoryDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = models.Category
    template_name = 'category_delete.html'
    success_url = reverse_lazy('category_list')  # Redireciona para a lista de categories após a exclusão
    permission_required = 'categories.change_category'


class CategoryCreateListAPIView(generics.ListCreateAPIView):
    queryset = models.Category.objects.all()
    serializer_class = serializers.CategorySerializer


class CategoryRetrieveUpdateDestroyAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = models.Category.objects.all()
    serializer_class = serializers.CategorySerializer

categories/templates/category_create.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Cadastrar Categoria</h3>
    <div class="card">
        <div class="card-body">
            <form method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Salvar Categoria</button>
            </form>
        </div>
    </div>
    <a href="{% url 'category_list' %}" class="btn btn-secondary mt-3">Cancelar e voltar</a>
</div>


{% endblock %}

categories/templates/category_delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4">
        <h3 class="display-6">Excluir Categoria</h3>

        <div class="card">
            <div class="card-body">
                <p class="card-text">Tem certeza que deseja excluir a Categoria <strong>"{{ object.name }}"</strong>?</p>
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger mt-3">Excluir</button>
                </form>
                <a href="{% url 'category_list' %}" class="btn btn-secondary mt-3">Cancelar e voltar</a>
            </div>
        </div>
{% endblock %}

categories/templates/category_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Detalhes da Categoria</h3>

    <div class="card">
        <div class="card-body">
            <h3 class="card-title">{{ object.name }}</h3>
            <p class="card-text">{{ object.description }}</p>
        </div>
    </div>
    <a href="{% url 'category_list' %}" class="btn btn-secondary mt-3">Voltar para a lista de Categorias</a>
</div>

{% endblock %}

categories/templates/category_list.html
{% extends 'base.html' %}

{% block title %}
SGE - Categorias
{% endblock %}

{% block content %}

<div class="row mb-3">
    <div class="col-md-6">
        <form method="get" action="{% url 'category_list' %}">
            <div class="input-group">
                <input type="text" class="form-control" name="name" placeholder="Nome" value="{{ request.GET.name }}">
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-search"></i>
                </button>
            </div>
        </form>
    </div>
    {% if perms.categories.add_category %}
        <div class="col-md-6">
            <a href="{% url 'category_create' %}" class="btn btn-success float-end">
                <i class="bi bi-plus-lg"></i> Nova Categoria
            </a>
        </div>
    {% endif %}
</div>

<div class="table-reponsive">
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr> <!-- Linha de cabeçalho da tabela -->
                <th>ID</th>
                <th>Nome</th>
                <th>Descrição</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for category in categories %} <!-- Loop para adicionar cada Categoria em uma linha -->
            <tr> <!-- Linha de dados da tabela -->
                <td>{{ category.id }}</td> <!-- o .id se refere ao nome dos campos definidos no models.py -->
                <td>{{ category.name }}</td>
                <td>{{ category.description }}</td>
                <td>
                    {% if perms.categories.view_category %}
                        <a href="{% url 'category_detail' category.id %}" class="btn btn-info btn-sm">
                            <i class="bi bi-eye"></i>
                        </a>
                    {% endif %}
                    {% if perms.categories.change_category %}
                        <a href="{% url 'category_update' category.id %}" class="btn btn-warning btn-sm">
                            <i class="bi bi-pencil"></i>
                        </a>
                    {% endif %}
                    {% if perms.categories.delete_category %}
                        <a href="{% url 'category_delete' category.id %}" class="btn btn-danger btn-sm">
                            <i class="bi bi-trash"></i>
                        </a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% include 'components/_pagination.html' %}

{% endblock %}

categories/templates/category_update.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Editar Categoria</h3>

    <div class="card">
        <div class="card-body">
            <form method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Salvar Categoria</button>
            </form>
        </div>
    </div>
    <a href="{% url 'category_list' %}" class="btn btn-secondary mt-3">Cancelar e voltar</a>
</div>

{% endblock %}